### ISSUE TITLE
Allow direct query against /stac/search instead of requiring a collection

### ISSUE THREAD

**Issue by philvarner** [kbgg/qgis-stac-browser#18]
It looks to me like the list of endpoints is built by retrieving all of the links to collections, and then creating one entry per collection.  I'd like to be able to run my queries against the "search" ref link in the /stac Catalog without needing to choose a collection.

**Comment by kbgg** [comment]
Closed by #21 
The plugin now does searches against the /stac/search endpoint but still requires a list of collections. The UI makes it one click to select all collections for an API which in effect does the same search as not requesting specific collections.

**Comment by philvarner** [comment]
I have to disagree about this.  This behavior assumes that the WFS 3 `/collections/{collection_id}` endpoints are implemented and referenced in the Catalog from `/stac` -- however, STAC does not mandate that the WFS 3 endpoints also be implemented. I would hope that this plugin would work against and api that only implemented STAC and not one that had to implement both STAC and WFS 3.

**Comment by kbgg** [comment]
Ah, I wasn't aware that in STAC the collection endpoints are not required to be implemented. I think I have an idea how I can work around this and still provide a good user experience so I'll play around with it a little bit and get back to this.
