### ISSUE TITLE
Select extent by current canvas extent or drawing a rectangle

### ISSUE THREAD

**Issue by suricactus** [kbgg/qgis-stac-browser#59]
The current layer extent only approach is very inconvenient in the general case.
Why limit only to layer extent, when you can use the current zoom level of the map canvas to get the extent? Further, the user should be also able to draw a rectangle extent on the map to be used.

Similar behavior control already exists in QGIS, however, it's part of the processing framework and it's not a reusable component (check the second param in "Clip raster by extent" algorithm). I would like to write it first for this plugin first and then maybe reimplement it directly in C++ to make it available to all plugin developers.

**Comment by kbgg** [comment]
I agree with this. Looks like a worthwhile feature to have!
